language: elixir
elixir:
- 1.4.2

sudo: required
dist: trusty

addons:
  postgresql: "9.6"

before_script:
- psql -c 'create database lift_dev_test;' -U postgres

deploy:
  - provider: script
    script: scripts/deploy
    on:
      branch: master

notifications:
  on_success: change
  on_failure: always
