version: "2"
services:
  api:
    build: .
    env_file: .env
    volumes:
    - /data/uploads:/uploads
    depends_on:
    - postgres
    ports:
    - 4000:4000
    links:
    - postgres
    environment:
    - MIX_ENV=prod
    - PORT=4000
    - POSTGRES_HOST=postgres
    - STORAGE_DIR=/uploads

  postgres:
    image: postgres:9.6.2
    volumes:
    - /data/postgres:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=lift_prod
